/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- crates/lab-pg/src/lib.rs:6
-- lab_pg::lab_answer
CREATE  FUNCTION "lab_answer"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'lab_answer_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/lab-pg/src/lib.rs:12
-- lab_pg::lab_version
CREATE  FUNCTION "lab_version"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'lab_version_wrapper';
/* </end connected objects> */

