#!/usr/bin/env bash
# Release phase 1, step 1a: derive and PROVE pgrx upgrade scripts, so the
# Release PR carries them the same way it carries the Cargo.toml bump and
# the changelog. Org canon — see docs/release.md (#132).
#
# The upgrade script is a build product, never authored. Both endpoints
# are fully known to the machinery: the previous schema ships inside the
# previous release's own signed tarball, and the candidate schema is
# generated by pgrx from the code being released. Asking a human to write
# or name this file is asking a human to author derived state — the same
# category error as hand-editing CHANGELOG.md — and it is what burned
# v0.16.0 and v0.16.2 in the lab. This is the pattern the largest
# publishers ship on (PostGIS and TimescaleDB both generate their upgrade
# scripts from the canonical schema at build time); pgrx itself declines
# to solve it, so the generation layer is ours.
#
# Derivation alone is not trusted: the script is proven before it is
# committed. A live Postgres installs the PREVIOUS release's real
# tarball, CREATE EXTENSION at the old version, overlays the candidate
# package plus the derived script, ALTER EXTENSION UPDATE — and the
# upgraded catalog must match a fresh install of the candidate EXACTLY,
# compared through pg_depend (pg_dump cannot see extension members; it
# dumps CREATE EXTENSION and nothing else). Anything the generator cannot
# soundly derive therefore fails THIS step — a red Release PR, before any
# tag exists — never the publish. The publish-time guard stays as the
# backstop for a tag minted around this path.
#
# Data migrations are the one thing no schema mechanism can derive. They
# go in an optional, version-free sql/next-data.sql beside the crate's
# other SQL; it is folded into the derived script (and removed by the
# release commit), and the round-trip proof applies to it like everything
# else.
#
# Expects the working tree AFTER prepare-release.sh: manifests already
# carry VERSION, so the candidate build names its schema correctly.
#
# Env in:  VERSION (bumped version), PREV_MANIFEST (pre-bump manifest
#          version, cross-checked against the published release),
#          GH_TOKEN, GITHUB_REPOSITORY.
# Writes GITHUB_OUTPUT key `files`: paths to add to the release commit.
set -euo pipefail

: "${VERSION:?VERSION must be set (the bumped version, no leading v)}"
: "${PREV_MANIFEST:=}"
: "${GH_TOKEN:?GH_TOKEN must be set}"
: "${GITHUB_REPOSITORY:?}"

canon="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

emit() {
  if [[ -n ${GITHUB_OUTPUT:-} ]]; then
    echo "$1" >> "${GITHUB_OUTPUT}"
  fi
}

# Applicability, detected never configured: a pgrx extension crate is the
# directory holding a checked-in <ext>.control file. No control files, no
# extension crates, nothing to derive — skip clean, per belt convention.
controls=()
# shellcheck disable=SC2312  # process substitution: capturing first would
# turn an empty result into one blank line, which is a worse bug than the
# masked status. The producing command is git/jq over local state.
while IFS= read -r tracked_control; do
  [[ -n ${tracked_control} ]] && controls+=("${tracked_control}")
done < <(git ls-files '*.control')
if ((${#controls[@]} == 0)); then
  echo "no extension control files tracked; pgrx upgrade derivation not applicable"
  emit "files="
  exit 0
fi

# What consumers actually run is recorded by the extension itself, not by
# the forge (#762). Every published version is the target of an upgrade
# script — `<ext>--<from>--<to>.sql` — so the highest `to` in that graph
# IS the latest version a database can be sitting on. That is the same
# source the repo-side upgrade-path lint reads, so the two agree by
# construction rather than by coincidence.
#
# This used to ask `gh release view` for the latest release and require
# its tag to look like `v<version>`. That is true of a repo which has
# always released under the canon and false of an imported one: edtf
# published eleven extension versions as `edtf-postgres-v1.2.3` and
# friends before its import, so the tag test read "first publish" and
# derived nothing, while the lint correctly demanded a path from 1.2.3
# (#669). A tag scheme is a fact about a repository's past; an upgrade
# graph is a fact about installations, and installations are what an
# upgrade path is for.
#
# An EMPTY graph is the only thing that means first publish.
prev=$(
  python3 - "${controls[@]}" << 'PYEOF'
import os, re, sys

def key(v):
    return tuple(int(part) for part in v.split("."))

best = None
for control in sys.argv[1:]:
    crate_dir = os.path.dirname(control)
    name = os.path.basename(control)[: -len(".control")]
    sql_dir = os.path.join(crate_dir, "sql")
    pattern = re.compile(
        r"^" + re.escape(name) + r"--(\d+\.\d+\.\d+)--(\d+\.\d+\.\d+)\.sql$"
    )
    try:
        entries = os.listdir(sql_dir)
    except FileNotFoundError:
        continue
    for entry in entries:
        match = pattern.match(entry)
        if not match:
            continue
        target = match.group(2)
        if best is None or key(target) > key(best):
            best = target
print(best or "")
PYEOF
)
if [[ -z ${prev} ]]; then
  echo "no upgrade graph; first publish of this extension needs no upgrade path"
  emit "files="
  exit 0
fi
if [[ ${prev} == "${VERSION}" ]]; then
  echo "upgrade graph already reaches ${VERSION}; nothing to derive"
  emit "files="
  exit 0
fi
if [[ -n ${PREV_MANIFEST} && ${PREV_MANIFEST} != "${prev}" ]]; then
  echo "NOTE: manifest carried ${PREV_MANIFEST} but the upgrade graph reaches ${prev}; deriving from ${prev}"
fi

# rust and cargo-pgrx are caller build inputs, pinned in the caller's own
# mise config — same read as build-pgrx-extension.yml.
pins=$(python3 -c '
import json, sys, tomllib
for candidate in ("mise.toml", ".mise.toml", "mise/config.toml"):
    try:
        with open(candidate, "rb") as f:
            t = tomllib.load(f)
        break
    except FileNotFoundError:
        continue
else:
    sys.exit("no mise config found")
tools = t.get("tools", {})
rust = tools.get("rust", "")
pgrx = tools.get("cargo:cargo-pgrx", "")
# A tool may be pinned as a LIST of versions — a repo that fuzzes declares
# a second, nightly toolchain beside the stable one so audit:fuzz can run
# AddressSanitizer (.github#445). mise puts the FIRST entry on PATH, and
# that is the toolchain this build must use; reading the list whole sent
# the entire JSON array to rustup as a version and reddened the lab
# Release PR on the first run after it declared one. No apostrophes in
# here: this block is a single-quoted python -c argument.
if isinstance(rust, list): rust = rust[0] if rust else ""
if isinstance(rust, dict): rust = rust.get("version", "")
print(json.dumps({"rust": rust, "pgrx": pgrx}))
')
RUST_VERSION=$(jq -r .rust <<< "${pins}")
PGRX_VERSION=$(jq -r .pgrx <<< "${pins}")
if [[ -z ${RUST_VERSION} || -z ${PGRX_VERSION} ]]; then
  echo "FAIL: rust and cargo:cargo-pgrx must be pinned in this repository's mise config" >&2
  exit 1
fi
export RUST_VERSION PGRX_VERSION

# One canonical cell derives the script: the newest PG major that both the
# base-image mapping carries and the previous release shipped, on the
# runner's own architecture. The script is pure SQL — identical across
# cells — and every cell still executes it at publish.
mapping=$(python3 -c '
import json, tomllib
with open("'"${canon}"'/docker/pgrx-base-images.toml", "rb") as f:
    t = tomllib.load(f)
print(json.dumps(t))
')

files_out=""

for control in "${controls[@]}"; do
  crate_dir=$(dirname "${control}")
  name=$(basename "${control}" .control)

  # Find the release that CARRIES the previous tarballs, rather than
  # assuming its tag (#762). For a repository that has always released
  # under the canon this is `v<prev>` and the search finds exactly that;
  # for an imported one the same bytes sit on whatever tag its old scheme
  # used — edtf's 1.2.3 extension tarballs are on `edtf-postgres-v1.2.3`,
  # and `v1.2.3` exists as a tag with no release object and therefore no
  # assets at all. Asking which release has the file is true in both
  # cases; asking which tag ought to have it is true in one.
  #
  # Only installations that can exist need a path: same carve-out as the
  # publish guard. A repo adding the class mid-life has a previous
  # release and no previous extension.
  prefix="${name}-${prev}-pg"
  prev_tag=$(gh api "repos/${GITHUB_REPOSITORY}/releases" --paginate \
    --jq "[.[] | select(.draft | not)
           | select(any(.assets[]; .name | startswith(\"${prefix}\")))
           | .tag_name] | first // empty")
  if [[ -z ${prev_tag} ]]; then
    echo "no published release carries ${name} ${prev} tarballs; first publish of this extension, no upgrade path needed"
    continue
  fi
  shipped=$(gh release view "${prev_tag}" --repo "${GITHUB_REPOSITORY}" \
    --json assets --jq \
    "[.assets[].name | select(startswith(\"${name}-${prev}-pg\"))]")

  pg=""
  for candidate_pg in $(jq -r '.build | keys | sort_by(tonumber) | reverse | .[]' <<< "${mapping}"); do
    if jq -e --arg a "${name}-${prev}-pg${candidate_pg}-linux-amd64.tar.gz" \
      'index($a)' <<< "${shipped}" > /dev/null; then
      pg="${candidate_pg}"
      break
    fi
  done
  if [[ -z ${pg} ]]; then
    echo "FAIL: ${prev_tag} shipped ${name} tarballs, but none for a PG major the base-image mapping carries" >&2
    exit 1
  fi
  build_image=$(jq -r --arg pg "${pg}" '.build[$pg]' <<< "${mapping}")

  work=$(mktemp -d)
  # mktemp -d is 0700 owned by the runner, and this directory is mounted
  # into the containers as /work. Both inner scripts drop to `postgres`
  # (pgrx refuses to run as root), and that user cannot traverse 0700 —
  # bash then reports "Permission denied" for a file it can otherwise
  # read, and the step dies with a bare exit 126. Chowning inside the
  # container is not an option for the proof pass, which mounts /work
  # read-only, so the traversal bit is set here, once, on the host.
  chmod 755 "${work}"
  mkdir -p "${work}/prevroot" "${work}/out"

  echo "deriving ${name}: ${prev} -> ${VERSION} (pg${pg})"
  gh release download "${prev_tag}" --repo "${GITHUB_REPOSITORY}" \
    --pattern "${name}-${prev}-pg${pg}-linux-amd64.tar.gz" \
    --output "${work}/prev.tar.gz"
  tar -xzf "${work}/prev.tar.gz" -C "${work}/prevroot"

  # -print -quit, never `| head -1`: find's own first-match stop, so
  # there is no pipe to break and no walk to finish (#682).
  prev_schema=$(find "${work}/prevroot" -type f -name "${name}--${prev}.sql" -print -quit)
  if [[ -z ${prev_schema} ]]; then
    echo "FAIL: ${prev_tag} tarball carries no generated schema ${name}--${prev}.sql" >&2
    exit 1
  fi

  # Build the candidate package inside the digest-pinned consumer
  # Postgres — same container, same pins, same layout as the build leg of
  # build-pgrx-extension.yml, minus the test suite (CI gates tests; this
  # leg needs only the generated schema and the loadable library).
  cat > "${work}/build.sh" << 'EOSH'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
  "postgresql-server-dev-${PG}" build-essential \
  ca-certificates curl pkg-config libclang-dev git
mkdir -p /build
cp -a /src/. /build/
chown -R postgres:postgres /build /work/out \
  "$(/usr/bin/pg_config --pkglibdir)" \
  "$(/usr/bin/pg_config --sharedir)/extension"
exec su -w PG,CRATE_DIR,RUST_VERSION,PGRX_VERSION \
  postgres -s /bin/bash /work/build-inner.sh
EOSH
  cat > "${work}/build-inner.sh" << 'EOSH'
set -euo pipefail
export HOME=/var/lib/postgresql
curl --proto "=https" --tlsv1.2 -sSf -o /tmp/rustup-init \
  "https://static.rust-lang.org/rustup/dist/$(uname -m)-unknown-linux-gnu/rustup-init"
chmod +x /tmp/rustup-init
/tmp/rustup-init -y --profile minimal \
  --default-toolchain "${RUST_VERSION}" --no-modify-path
. "${HOME}/.cargo/env"
cargo install cargo-pgrx --version "${PGRX_VERSION}" --locked
cargo pgrx init "--pg${PG}" /usr/bin/pg_config
cd "/build/${CRATE_DIR}"
export CARGO_INCREMENTAL=0
cargo pgrx package \
  --no-default-features --features "pg${PG}" \
  --pg-config /usr/bin/pg_config \
  --out-dir /work/out/pkgroot
EOSH
  docker run --rm \
    --env PG="${pg}" --env CRATE_DIR="${crate_dir}" \
    --env RUST_VERSION --env PGRX_VERSION \
    --volume "${PWD}:/src:ro" \
    --volume "${work}:/work" \
    "${build_image}" \
    bash /work/build.sh

  # -print -quit, never `| head -1`: find's own first-match stop, so
  # there is no pipe to break and no walk to finish (#682).
  new_schema=$(find "${work}/out/pkgroot" -type f -name "${name}--${VERSION}.sql" -print -quit)
  if [[ -z ${new_schema} ]]; then
    echo "FAIL: candidate build produced no generated schema ${name}--${VERSION}.sql" >&2
    exit 1
  fi

  data_fragment=""
  if [[ -f "${crate_dir}/sql/next-data.sql" ]]; then
    data_fragment="${crate_dir}/sql/next-data.sql"
  fi

  # Derive. The generator understands pgrx's own regular, deterministic
  # output — not arbitrary SQL — and fails loudly on anything it cannot
  # soundly migrate, naming the statement. The round-trip proof below is
  # the authority either way.
  EXT_NAME="${name}" PREV_V="${prev}" NEW_V="${VERSION}" \
    python3 - "${prev_schema}" "${new_schema}" "${work}/upgrade.sql" \
    ${data_fragment:+"${data_fragment}"} << 'EOPY'
import os
import re
import sys

prev_path, new_path, out_path = sys.argv[1:4]
data_path = sys.argv[4] if len(sys.argv) > 4 else ""
ext = os.environ["EXT_NAME"]
prev_v = os.environ["PREV_V"]
new_v = os.environ["NEW_V"]


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


DOLLAR = re.compile(r"\$[A-Za-z0-9_]*\$")
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)


def strip_leading_comments(stmt):
    """pgrx prefixes statements with `-- src/...` lines and opens the file
    with a /* banner */ that glues onto the first statement."""
    stmt = stmt.strip()
    while True:
        if stmt.startswith("/*"):
            end = stmt.find("*/")
            if end < 0:
                sys.exit(f"FAIL: unterminated block comment: {stmt[:200]!r}")
            stmt = stmt[end + 2:].lstrip()
        elif stmt.startswith("--"):
            nl = stmt.find("\n")
            if nl < 0:
                return ""
            stmt = stmt[nl + 1:].lstrip()
        else:
            return stmt


def split_statements(text):
    """Split on statement-terminating semicolons, dollar-quote aware."""
    stmts, buf, tag = [], [], None
    for line in text.splitlines():
        buf.append(line)
        for m in DOLLAR.finditer(line):
            if tag is None:
                tag = m.group(0)
            elif m.group(0) == tag:
                tag = None
        if tag is None and line.rstrip().endswith(";"):
            stmt = strip_leading_comments("\n".join(buf))
            buf = []
            if stmt:
                stmts.append(stmt)
    if strip_leading_comments("\n".join(buf)):
        sys.exit(f"FAIL: unterminated statement in generated schema: {buf[0][:200]!r}")
    return stmts


def norm(stmt):
    body = "\n".join(
        l for l in stmt.splitlines() if not l.strip().startswith("--")
    )
    body = BLOCK_COMMENT.sub(" ", body)
    return re.sub(r"\s+", " ", body).strip().rstrip(";")


def paren_span(text, start):
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i
    sys.exit(f"FAIL: unbalanced parentheses in: {text[:200]!r}")


# pgrx emits "CREATE  FUNCTION" (double space): match on \s+, always.
FUNC_RE = re.compile(r"^CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+", re.I)


def func_parts(n):
    m = FUNC_RE.match(n)
    rest = n[m.end():]
    p = rest.index("(")
    close = paren_span(rest, p)
    name = rest[:p].strip()
    args = rest[p:close + 1]
    after = rest[close + 1:].strip()
    return name, args, after


def drop_sig(name, args):
    """name(arg, arg, ...) with DEFAULT clauses stripped — Postgres
    ignores argument names in DROP FUNCTION but refuses defaults."""
    inner = args[1:-1]
    parts, depth, cur = [], 0, []
    for ch in inner:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    if cur:
        parts.append("".join(cur))
    cleaned = []
    for a in parts:
        a = re.split(r"\sDEFAULT\s", a, flags=re.I)[0].strip()
        if a:
            cleaned.append(a)
    return f"{name}({', '.join(cleaned)})"


def returns_region(after):
    """The text between the argument list and LANGUAGE — a change here
    means CREATE OR REPLACE would be refused, so drop-and-recreate."""
    return re.split(r"\bLANGUAGE\b", after, flags=re.I)[0].strip()


# Named object kinds: creatable when new, droppable by name when removed,
# and REFUSED when changed — an in-place change to one of these is not
# derivable from two schemas (it may need data-aware DDL), so it must be
# provided via sql/next-data.sql, visibly.
NAMED_KINDS = [
    ("CREATE TYPE ", "TYPE"),
    ("CREATE SCHEMA ", "SCHEMA"),
    ("CREATE TABLE ", "TABLE"),
    ("CREATE UNLOGGED TABLE ", "TABLE"),
    ("CREATE VIEW ", "VIEW"),
    ("CREATE SEQUENCE ", "SEQUENCE"),
]
# Always safe to re-apply.
REPLAY = ("COMMENT ON ", "GRANT ", "REVOKE ")


def classify(stmt):
    n = norm(stmt)
    u = n.upper()
    if FUNC_RE.match(n):
        name, args, after = func_parts(n)
        return ("function", drop_sig(name, args).upper(), n)
    for prefix, kind in NAMED_KINDS:
        if u.startswith(prefix):
            rest = n[len(prefix):]
            m = re.match(r"[^\s(;]+", rest)
            if not m:
                sys.exit(f"FAIL: cannot name {kind} in: {n[:200]!r}")
            return ("named", (kind, m.group(0)), n)
    for prefix in REPLAY:
        if u.startswith(prefix):
            return ("replay", n, n)
    # Everything else (extension_sql! blocks, ALTER, INSERT, DO, operator
    # machinery, aggregates, casts, ...) is opaque: fine while identical
    # across versions (the previous install already ran it), underivable
    # when it appears, changes or disappears.
    return ("opaque", n, n)


def index(stmts):
    funcs = {}
    named = {}
    other = {}
    order = []
    for s in stmts:
        cls, key, n = classify(s)
        order.append((cls, key, n, s))
        if cls == "function":
            funcs[key] = n
        elif cls == "named":
            named.setdefault(key, []).append(n)
        else:
            other.setdefault(n, 0)
            other[n] += 1
    return funcs, named, other, order


prev_stmts = split_statements(read(prev_path))
new_stmts = split_statements(read(new_path))
p_funcs, p_named, p_other, p_order = index(prev_stmts)
n_funcs, n_named, n_other, n_order = index(new_stmts)

failures = []
body = []

# Drops, in reverse creation order of the previous schema — the closest
# thing to a correct destroy order two schemas can offer. Anything it
# gets wrong fails the round-trip proof, red on the Release PR.
drops = []
seen_named_drop = set()
for cls, key, n, _ in p_order:
    if cls == "function" and key not in n_funcs:
        name, args, _ = func_parts(n)
        drops.append(f"DROP FUNCTION {drop_sig(name, args)};")
    elif cls == "named" and key not in n_named and key not in seen_named_drop:
        seen_named_drop.add(key)
        kind, obj = key
        drops.append(f"DROP {kind} {obj};")
    elif cls == "opaque" and n not in n_other:
        failures.append(
            f"statement removed since {prev_v} and not derivable: {n[:160]!r}"
        )
drops.reverse()

for cls, key, n, s in n_order:
    if cls == "function":
        prev_n = p_funcs.get(key)
        if prev_n == n:
            continue
        stmt = FUNC_RE.sub("CREATE OR REPLACE FUNCTION ", s.strip(), count=1)
        if prev_n is not None:
            _, _, p_after = func_parts(prev_n)
            _, _, n_after = func_parts(n)
            if returns_region(p_after) != returns_region(n_after):
                name, args, _ = func_parts(n)
                body.append(f"DROP FUNCTION {drop_sig(name, args)};")
        body.append(stmt if stmt.rstrip().endswith(";") else stmt + ";")
    elif cls == "named":
        if key in p_named:
            if p_named[key] != n_named[key]:
                kind, obj = key
                failures.append(
                    f"{kind} {obj} changed since {prev_v}; in-place changes "
                    "to this kind are not derivable — provide the migration "
                    "in sql/next-data.sql"
                )
            continue
        body.append(s if s.rstrip().endswith(";") else s + ";")
    elif cls == "replay":
        if n in p_other:
            continue
        body.append(s if s.rstrip().endswith(";") else s + ";")
    else:  # opaque
        if n in p_other:
            continue
        failures.append(
            f"statement new since {prev_v} and not derivable: {n[:160]!r}"
        )

# Underivable changes end the derivation — unless the author shipped a
# sql/next-data.sql fragment, which is the explicit declaration that the
# underivable part is handled there. The declaration is not trusted: the
# round-trip proof compares the upgraded catalog against a fresh install
# either way, so a fragment that does not actually close the gap still
# fails the Release PR.
if failures:
    if not data_path:
        for f in failures:
            print(f"::error::{ext}: {f}", file=sys.stderr)
        sys.exit(1)
    for f in failures:
        print(
            f"::warning::{ext}: {f} — assuming sql/next-data.sql handles it; "
            "the round-trip proof decides",
            file=sys.stderr,
        )

data = ""
if data_path:
    data = read(data_path).strip()

lines = [
    f"\\echo Use \"ALTER EXTENSION {ext} UPDATE TO '{new_v}'\" to load this file. \\quit",
    "",
    f"-- Derived by release/generate-pgrx-upgrade.sh: {prev_v} -> {new_v}.",
    "-- DO NOT EDIT. Regenerated on every Release-PR refresh from the",
    f"-- published v{prev_v} schema and the v{new_v} build, and proven by",
    "-- ALTER EXTENSION UPDATE against a live installation before commit.",
    "",
]
if not drops and not body and not data:
    lines.append(f"-- No schema change between {prev_v} and {new_v}: this")
    lines.append("-- release alters only the compiled library.")
else:
    lines.extend(drops)
    if drops and body:
        lines.append("")
    lines.extend(body)
    if data:
        lines.append("")
        lines.append("-- Authored data migration for this cycle (sql/next-data.sql):")
        lines.append(data)

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
EOPY

  # Prove it: the exact consumer sequence, then catalog equality. pg_dump
  # cannot see extension members, so equality is read from pg_depend with
  # per-kind definitions.
  cat > "${work}/snapshot.sql" << 'EOSQL'
SELECT pg_identify_object(d.classid, d.objid, 0)::text
       || ' | ' ||
       CASE
         WHEN d.classid = 'pg_proc'::regclass AND p.prokind = 'f'
           THEN pg_get_functiondef(d.objid)
         WHEN d.classid = 'pg_proc'::regclass
           THEN p.prokind || ':' || pg_get_function_identity_arguments(d.objid)
         WHEN d.classid = 'pg_type'::regclass
           THEN t.typtype || ':' || t.typlen || ':' || t.typcategory
                || ':' || t.typinput::text || ':' || t.typoutput::text
         ELSE ''
       END
FROM pg_depend d
LEFT JOIN pg_proc p ON d.classid = 'pg_proc'::regclass AND p.oid = d.objid
LEFT JOIN pg_type t ON d.classid = 'pg_type'::regclass AND t.oid = d.objid
WHERE d.refclassid = 'pg_extension'::regclass
  AND d.refobjid = (SELECT oid FROM pg_extension WHERE extname = :'ext')
  AND d.deptype = 'e'
ORDER BY 1
EOSQL
  cat > "${work}/proof.sh" << 'EOSH'
set -euo pipefail
lib="/usr/lib/postgresql/${PG}/lib"
ext="/usr/share/postgresql/${PG}/extension"
cp -a "/prev${lib}/." "${lib}/"
cp -a "/prev${ext}/." "${ext}/"
su -w PG,NAME,PREV postgres -s /bin/bash -c '
  set -euo pipefail
  bin="/usr/lib/postgresql/${PG}/bin"
  "${bin}/initdb" -D /tmp/pgdata -A trust > /dev/null
  "${bin}/pg_ctl" -D /tmp/pgdata -o "-c listen_addresses=" -w start > /dev/null
  createdb upgraded
  psql -d upgraded -c "CREATE EXTENSION ${NAME} VERSION '\''${PREV}'\'';" > /dev/null
'
# The candidate package lands over the old — exactly what a package
# upgrade does — together with the derived script under proof.
cp -a "/new${lib}/." "${lib}/"
cp -a "/new${ext}/." "${ext}/"
cp /work/upgrade.sql "${ext}/${NAME}--${PREV}--${NEW}.sql"
su -w PG,NAME,PREV,NEW postgres -s /bin/bash -c '
  set -euo pipefail
  psql -d upgraded -c "ALTER EXTENSION ${NAME} UPDATE TO '\''${NEW}'\'';" > /dev/null
  got=$(psql -d upgraded -tA -c \
    "SELECT extversion FROM pg_extension WHERE extname = '\''${NAME}'\'';")
  if [[ ${got} != "${NEW}" ]]; then
    echo "::error::upgrade left extversion ${got}, wanted ${NEW}"
    exit 1
  fi
  createdb fresh
  psql -d fresh -c "CREATE EXTENSION ${NAME} VERSION '\''${NEW}'\'';" > /dev/null
  psql -d upgraded -tA -v ext="${NAME}" -f /work/snapshot.sql > /tmp/upgraded.snap
  psql -d fresh -tA -v ext="${NAME}" -f /work/snapshot.sql > /tmp/fresh.snap
  if ! diff -u /tmp/upgraded.snap /tmp/fresh.snap; then
    emsg="::error::upgraded ${NAME} catalog differs from a fresh ${NEW} install — the derived script is"
    emsg+=" unsound; see the diff above"
    echo "${emsg}"
    exit 1
  fi
  echo "proof: ${NAME} ${PREV} -> ${NEW} upgraded catalog identical to fresh install"
'
EOSH
  docker run --rm \
    --env PG="${pg}" --env NAME="${name}" \
    --env PREV="${prev}" --env NEW="${VERSION}" \
    --volume "${work}/prevroot/pkgroot:/prev:ro" \
    --volume "${work}/out/pkgroot:/new:ro" \
    --volume "${work}:/work:ro" \
    "${build_image}" \
    bash /work/proof.sh

  mkdir -p "${crate_dir}/sql"
  cp "${work}/upgrade.sql" "${crate_dir}/sql/${name}--${prev}--${VERSION}.sql"
  files_out="${files_out} ${crate_dir}/sql/${name}--${prev}--${VERSION}.sql"
  echo "upgrade path derived and proven: ${crate_dir}/sql/${name}--${prev}--${VERSION}.sql"

  # The data fragment is consumed by this cycle: it leaves the tree in the
  # same release commit that ships its content inside the derived script.
  if [[ -n ${data_fragment} ]]; then
    rm "${data_fragment}"
    files_out="${files_out} ${data_fragment}"
  fi

  # The build container chowns /work/out to postgres, so its files — and
  # the directories holding them — come back owned by a container uid the
  # runner cannot write to, and a plain rm -rf dies with Permission denied
  # AFTER the upgrade script has already been derived, proven and copied.
  # Hand ownership back from inside the same image (already pulled, so no
  # extra network) rather than reaching for sudo, which this script should
  # not need and would not have outside a runner.
  # shellcheck disable=SC2312  # id(1) on the local uid cannot meaningfully fail
  docker run --rm --volume "${work}:/work" "${build_image}" \
    chown -R "$(id -u):$(id -g)" /work
  rm -rf "${work}"
done

emit "files=${files_out# }"
